---
title: "Assn4"
author: "Berdimyrat Mammedov"
date: "February 10, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Just make sure that working directory is the
```{r}
setwd("C:/Users/berdi/OneDrive/Documents/datasciencecoursera")
getwd()
```


## R Markdown

```{r}
file_url <- "https://d396qusza40orc.cloudfront.net/rprog%2Fdata%2Fspecdata.zip"
download.file(file_url, "specdata.zip")
unzip("specdata.zip", exdir= "/.")

```

##List data in folder

```{r}
list.files("specdata")
```


##Pollutantmean function
```{r}
pollutantmean <- function(directory, pollutant = "sulfate", id = 1:332) {
    
    out_mean <- c()
   
files <- list.files("./specdata")

filePath <- paste("./specdata/", files, sep="")
  
  for (i in id) {
    data <- read.table(filePath[i], header = T, sep= ",", stringsAsFactors = FALSE)
    clean_data <- data[!is.na(data[,pollutant]), pollutant]
    out_mean <- c(out_mean, clean_data)
  }
output <- mean(out_mean)

}


```



```{r}

complete <- function(directory, id = 1:332) {
    
    files <- list.files("./specdata")

    filePath <- paste("./specdata/", files, sep="")
    completes <- c()
    z <- 1
    for (i in id) {
        data <- read.table(filePath[i], header = TRUE, sep = ",")
        completes[z] <- sum(complete.cases(data))
        z <- z+1
    }
    #Creating a dataFrame id - nobs
    data.frame(id = id, nobs = completes)
}

test <- complete("specdata", 1:5)
test
```


# Correlation Part 3
```{r}
correlation <- function(directory = "./specdata/" , threshold = 0) {

       
    files <- list.files("./specdata")

    filePath <- paste("./specdata/", files, sep="")
    
    completeFrame <- complete(directory)
    validId <- completeFrame$id[completeFrame$nobs>threshold]
    
    
    correlations <- c()
    z <- 1
    for (i in validId) {
        data <- read.table(filePath[i], header = TRUE, sep = ",")
        correlations[z] <- cor(data$sulfate, data$nitrate, use = "na.or.complete")
        z <- z+1
    }
   correlations 
   }

test <- correlation()


test
```





















